# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='item_website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
