# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newswebsite',
            name='language',
            field=models.CharField(blank=True, choices=[('ar', 'Arabic'), ('en', 'English')], max_length=2, null=True),
        ),
    ]
