# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 08:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190505_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 11, 23, 9, 679863)),
        ),
    ]
